services:
  - type: web
    name: us-web-app-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://us-web-app-be.onrender.com